/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ComentarioSchema extends BaseModel {
  static $columns = ['comentario', 'createdAt', 'id', 'jugadorId', 'partidoId', 'updatedAt'] as const
  $columns = ComentarioSchema.$columns
  @column()
  declare comentario: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jugadorId: number
  @column()
  declare partidoId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class HistorialPozoSchema extends BaseModel {
  static $columns = ['afectado', 'createdAt', 'descripcion', 'id', 'pozoId', 'tipoMoviento', 'updatedAt'] as const
  $columns = HistorialPozoSchema.$columns
  @column()
  declare afectado: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare descripcion: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pozoId: number
  @column()
  declare tipoMoviento: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JugadoreSchema extends BaseModel {
  static $columns = ['alias', 'correo', 'createdAt', 'id', 'nombre', 'numeroContacto', 'updatedAt'] as const
  $columns = JugadoreSchema.$columns
  @column()
  declare alias: string | null
  @column()
  declare correo: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column()
  declare numeroContacto: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PartidoSchema extends BaseModel {
  static $columns = ['adminDni', 'adminPin', 'createdAt', 'cupoMax', 'cvuAliasLink', 'id', 'inicioPartido', 'invitacion', 'status', 'ubicacion', 'updatedAt'] as const
  $columns = PartidoSchema.$columns
  @column()
  declare adminDni: string
  @column()
  declare adminPin: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cupoMax: number
  @column()
  declare cvuAliasLink: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare inicioPartido: DateTime
  @column()
  declare invitacion: string
  @column()
  declare status: string
  @column()
  declare ubicacion: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PartidosJugadoreSchema extends BaseModel {
  static $columns = ['createdAt', 'estadoReserva', 'id', 'jugadorId', 'partidoId', 'updatedAt'] as const
  $columns = PartidosJugadoreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare estadoReserva: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jugadorId: number
  @column()
  declare partidoId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PozoSchema extends BaseModel {
  static $columns = ['costoTotal', 'createdAt', 'id', 'partidoId', 'pozoPadre', 'recaudado', 'updatedAt'] as const
  $columns = PozoSchema.$columns
  @column()
  declare costoTotal: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare partidoId: number
  @column()
  declare pozoPadre: number | null
  @column()
  declare recaudado: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
